- name: install specific packages via chocolatey
  hosts: all

  vars:
  - package_action: present

  - packages_to_install:
      firefox
      notepadplusplus.install
      7zip.install
      putty.install
      clash-of-clans

  tasks:
  - name: "Assure packages are {{ package_action }}"
    win_chocolatey:
      name: "{{ packages_to_install }}"
      state: "{{ package_action }}"
