---
- name: Build a VMware guest from template
  hosts: localhost
  gather_facts: no

  roles:
    - kev-vmware-provision

- hosts: newlyprovisionedvm
  roles:
    - kev-motd
    - kev-nano
    - kev-screen
    - kev-standardsoftware
    - kev-users

