---
- name: MAIN | Deploying subtasks
  hosts: all
  remote_user: root
  vars:
    install_packages:
    - libselinux-python
    - nmap
    - nano
    - ntp
    - screen
    - sysstat

  tasks:
    - include: plays/motd_customize.yaml

    - include: plays/package_install.yaml

    - include: plays/users.yaml

    - include: plays/figlet.yaml

    - include: plays/cowsay.yaml
      when: ansible_cmdline["COWSAY"] is defined and ansible_cmdline["COWSAY"] == 'yes'

    - name: Remove the service that automatically started this playbook
      file: path=/usr/lib/systemd/system/ansible-firstboot.service state=absent

