---
- name: MAIN | Deploying subtasks
  hosts: all
  remote_user: root
  vars:
    install_packages:
    - libselinux-python
    - nmap
    - nano
    - ntp
    - screen
    - sysstat

  tasks:
    - include: plays/motd_customize.yaml

    - include: plays/package_install.yaml

    - include: plays/users.yaml

    - include: plays/figlet.yaml

#    - include: plays/cowsay.yaml
#      when: ansible_cmdline["COWSAY"] is defined and ansible_cmdline["COWSAY"] == 'yes'

    - name: Remove the service that automatically started this playbook for RHEL7
      file: path=/usr/lib/systemd/system/ansible-firstboot.service state=absent
      ignore_errors: yes

    - name: Remove the service that automatically started this playbook for RHEL6
      file: path=/etc/rc.d/rc3.d/S99ansible-firstboot state=absent
      ignore_errors: yes

    - name: Reboot server
      command: /sbin/reboot
      when: rebootrequired is defined and rebootrequired == 'yes'

    - name: Wait for the server to finish rebooting
      sudo: no
      local_action: wait_for host="{{ inventory_hostname }}" search_regex=OpenSSH port=22 timeout=300
      when: rebootrequired is defined and rebootrequired == 'yes'

