---
- name: MAIN | Deploying subtasks
  hosts: all
  remote_user: root
  vars:
    install_packages:
    - libselinux-python
    - nmap
    - nano
    - ntp
    - screen
    - sysstat

  tasks:
    - include: plays/motd_customize.yaml
      when: ansible_distribution[ANSIBLERUN] is defined and ansible_distribution[ANSIBLERUN] == 'yes'

    - include: plays/package_install.yaml
      when: ansible_distribution[ANSIBLERUN] is defined and ansible_distribution[ANSIBLERUN] == 'yes'

    - include: plays/users.yaml
      when: ansible_distribution[ANSIBLERUN] is defined and ansible_distribution[ANSIBLERUN] == 'yes'

    - include: plays/figlet.yaml
      when: ansible_distribution[ANSIBLERUN] is defined and ansible_distribution[ANSIBLERUN] == 'yes'

