- name: install specific RPMs
  hosts: all
  remote_user: root

    tasks:
    - include: includes/package_list.yaml

    - name: install packages with yum
      yum:
        name: "{{ item }}"
        state: latest
      with_items: "{{ install_packages }}"
