- name: install specific RPMs
  hosts: all
  remote_user: root

  vars:
    install_packages:
      - nano
      - screen

    tasks:
    - name: install packages with yum
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ install_packages }}"
      ignore_errors: yes
