---
- name: Build a VMware guest from template
  hosts: localhost
  gather_facts: no
  tasks:
  - include_role:
      name: vmware-provision

- name: Standardize the new vm
  hosts: newlinuxvm
  vars:
  - motd_template_file: templates/motd_gokev_bw
  roles:
  - rhel-subscribe-employee-sku
  - prep-new-vm
  - vm-reboot
  - motd-splash
  - kev-nano

- name: Standardize the new windows vm
  hosts: newwindowsvm
  roles:
  - prep-new-windows
  - chocolatey_client

