---
- name: Build a VMware guest from template
  hosts: localhost
  gather_facts: no
  tasks:

  - name: Match OS for Linux
    set_fact:
      os_type: linux
    when: vm_template | regex_search('(?i)^.*[rhel|cent].*$')

  - name: Match OS for Windows
    set_fact:
      os_type: windows
    when: vm_template | regex_search('(?i)^.*win.*$')

  - include_role:
      name: vmware-provision





- name: Standardize the new linux vm
  hosts: newlinuxvm
  vars:
  - motd_template_file: templates/motd_gokev_bw
  roles:
  - rhel-subscribe-employee-sku
  - prep-new-linux
  - vm-reboot
  - motd-splash
  - kev-nano

- name: Standardize the new windows vm
  hosts: newwindowsvm
  roles:
  - prep-new-windows
#  - chocolatey_client

