---
- name: Build a VMware guest from template
  hosts: localhost
  gather_facts: no

  tasks:
  - include_role:
      name: vmware-provision

- name: Standardize the new vm
  hosts: newvm

  vars:
  - motd_template_file: templates/motd_gokev_bw

  roles:
  - prep-new-vm
  - motd-splash
  - vm-reboot


