---
- name: Build a VMware guest from template
  hosts: localhost
  gather_facts: no

  tasks:
  - include_role:
      name: vmware-provision

- name: Standardize the new vm
  hosts: newlinuxvm

  vars:
  - motd_template_file: templates/motd_gokev_bw

  roles:
  - prep-new-vm
  - vm-reboot
  - motd-splash


- name: Standardize the new windows vm
  hosts: newwindowsvm

  tasks:
  - debug:
      msg: "Running a role against {{ ansible_host }} inside vmware-provision.yml but nothing is defined.  Exiting now."
