- name: perform windows updates
  hosts: all

  vars:

  tasks:
  - name: Install only particular updates based on the KB numbers
    win_updates:
      category_name:
      - SecurityUpdates
      whitelist:
      - KB4056892
      - KB4073117

  - name: Exclude updates based on the update title
    win_updates:
      category_name:
      - SecurityUpdates
      - CriticalUpdates
      blacklist:
      - Windows Malicious Software Removal Tool for Windows
      - \d{4}-\d{2} Cumulative Update for Windows Server 2016

