---
- name: "Deploy new VM called {{ item.vm_name }}"
  vmware_guest:
    datacenter: "{{ vmware_datacenter }}"
    cluster: "{{ vmware_cluster }}"
    resource_pool: "{{ vmware_resource_pool }}"
    name: "{{ item.vm_name }}"
    template: "{{ vmware_template_name }}"
    linked_clone: True
    wait_for_ip_address: no
    folder: "{{ vmware_folder }}"
    state: "{{ vmware_state }}"

    disk:
    - size_gb: "{{ vmware_disk_size }}"
      type: thin
      datastore: "{{ vmware_datastore }}"

    hardware:
      memory_mb: "{{ vmware_ram_mb }}"
      num_cpus: "{{ vm_cpu_count }}"

    networks:
    - name: "{{ vmware_network }}"
      ip: "{{ item.vm_ip }}"
      netmask: "{{ item.vm_mask }}"
  with_items:  "{{ vmware_new_machines }}"
  delegate_to: localhost
  changed_when: False



- name: Revert to a NEKD snapshot
  vmware_guest_snapshot:
    datacenter: "{{ vmware_datacenter }}"
    folder: "{{ vmware_folder }}"
    name: "{{ item.vm_name }}"
    state: revert
    snapshot_name: NEKD
  with_items:  "{{ vmware_new_machines }}"
  delegate_to: localhost
  changed_when: False

