---
# tasks file for prep-tower-cluster

- name: Disable IPv6 with sysctl
  sysctl: name={{ item }} value=1 state=present
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6
  failed_when: no

#- name: Packages to install
#  yum:
#    name:
#      - nano
#      - wget
#    state: present

- name: "set hostname to {{ name_fqdn }}"
  hostname:
    name: "{{ name_fqdn }}"

- name: Match template to a partition schema for CentOS7
  set_fact:
    fdisk_answerfile: files/fdisk_answers_p2.txt
#  when: vm_template | match("*cent*7*")

#- name: Match template to a partition schema for CentOS8
#  set_fact:
#    fdisk_answerfile: files/fdisk_answers_p3.txt
#  when: vm_template | match("*cent*8*")

#- name: Match template to a partition schema for RHEL8
#  set_fact:
#    fdisk_answerfile: files/fdisk_answers_p3.txt
#  when: vm_template | match("*rhel*8*")

- name: put the fdisk answer file in place
  copy:
    src: {{ fdisk_answerfile }}
    dest: /tmp/answers

- name: expand partitions with fdisk
  raw: 'fdisk /dev/sda < /tmp/answers'
  failed_when: no

- name: probe partitions with partprobe
  raw: 'partprobe'
  failed_when: no

- name: expand the xfs filesystem
  raw: xfs_growfs /

#  filesystem:
#    fstype: xfs
#    dev: /dev/sda3
#    resizefs: yes
#  failed_when: no

- name: remove the fdisk answer file
  file:
    path: /tmp/answers
    state: absent

