---
# tasks file for chocolatey_client

- name: Install the chocolatey command
  win_shell: |
    Set-ExecutionPolicy Bypass -Scope Process -Force; 
    iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

- name: Add new internal source
  win_chocolatey_source:
    name: GoKEV Lab Chocolatey Repo
    source: http://10.0.30.70/chocolatey
    state: present

- name: Disable Chocolatey source
  win_chocolatey_source:
    name: chocolatey
    state: disabled

