- set_fact:
    new_vm_names: "{{ vm_name }}"
    cacheable: yes
    when: "{{ new_vm_names }}" is undefined

- include_tasks: "{{ os_type }}.yml" "newname={{ vm_name }}"
  with_items: "{{ new_vm_names }}"

