- include_tasks: "{{ os_type }}.yml"
  vars:
    new_vm_name: "{{ item }}"
  with_items: "{{ new_vm_names }}"
  when: new_vm_names is defined and (new_vm_names|length<1)

- include_tasks: "{{ os_type }}.yml"
  vars:
    new_vm_name: "{{ vm_name }}"
  when: (new_vm_names|length>0)
