- set_fact:
    new_vm_names:
    - one
    - two

- include_tasks: "{{ os_type }}.yml"
  vars:
    new_vm_name: "{{ vm_name }}"
  with_items: "{{ new_vm_names }}"
  when: new_vm_names is defined

- include_tasks: "{{ os_type }}.yml"
  vars:
    new_vm_name: "{{ vm_name }}"
  when: new_vm_names is undefined
