---
# tasks file for prep-tower-cluster

- name: Disable IPv6 with sysctl
  sysctl: name={{ item }} value=1 state=present
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6
  failed_when: no

- name: Packages to install
  yum:
    name:
      - nano
      - wget
    state: present

- name: "set hostname to {{ inventory_hostname }}"
  hostname:
    name: "{{ inventory_hostname }}"

- name: expand the filesystem if possible
  filesystem:
    fstype: xfs
    dev: /dev/sda2
    resizefs: yes

