---
- name: Standardized root account
  user:
    name: root
    password: '$5$UJVcZzAe$4i6jlDxECSe9t8L5Kt/ZFhPPinuiyOjeW8kjVGKPrED'
    generate_ssh_key: yes

- name: Make sure the .ssh dir is in place
  file:
    path: /root/.ssh/
    state: directory
    owner: root
    group: wheel
    mode: 0700

- name: authorized_keys file for root
  copy:
    src: templates/authorized_keys
    dest: /root/.ssh/authorized_keys
    owner: root
    group: wheel
    mode: 0600
    backup: yes

- name: sshd_config file
  copy:
    src: templates/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: wheel
    mode: 0600
    backup: yes

