---
- name: MAIN | Deploying subtasks
  hosts: all
  remote_user: root
  gather_facts: yes

  tasks:

  - name: include role kev-figlet
    include_role:
      name: kev-figlet
    tags:
    - kev-figlet

  - name: include role kev-motd
    include_role:
      name: kev-motd
    tags:
    - kev-motd

  - name: include role kev-nano
    include_role:
      name: kev-nano
    tags:
    - kev-nano

  - name: include role kev-satelliteclientreg
    include_role:
      name: kev-satelliteclientreg
    tags:
    - kev-satelliteclientreg

  - name: include role kev-screen
    include_role:
      name: kev-screen
    tags:
    - kev-screen

  - name: include role kev-standardsoftware
    include_role:
      name: kev-standardsoftware
    tags:
    - kev-standardsoftware

  - name: include role kev-users
    include_role:
      name: kev-users
    tags:
    - kev-users


## If we called for a reboot, we do that here in tasks

    - name: reboot host RHEL6 if we call for a reboot
      command: sleep 5 ; /sbin/shutdown -r ; echo &
      when: rebootrequired is defined and rebootrequired == 'yes' and ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

    - name: reboot host RHEL7 if we call for a reboot
      command: /usr/bin/systemd-run --on-active=10 /usr/bin/systemctl reboot
      async: 0
      poll: 0
      when: rebootrequired is defined and rebootrequired == 'yes' and ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

    - name: wait for host sshd if we call for a reboot
      local_action: wait_for host="{{ ansible_hostname }}" search_regex=OpenSSH port=22 timeout=300 delay=90
      when: rebootrequired is defined and rebootrequired == 'yes' and ansible_os_family == "RedHat"

#    - name: Display conditionals for this request
#      debug:
#        msg: "rebootrequired is {{ rebootrequired }} and ansible_os_family is {{ ansible_os_family }} and ansible_distribution_major_version is {{ ansible_distribution_major_version }}"
#
#    - name: Display all variables/facts known for a host
#      debug: var=hostvars[inventory_hostname] verbosity=4

