---
- name: Build a VMware guest from template
  hosts: all
  connection: local
  gather_facts: no

  tasks:
  - name: "kev-vmware-provision if {{ newvmip } is not defined"
    include_role:
      name: kev-vmware-provision
    when: ! newvmip is defined

  - name: applying remaining roles to "{{ newvmip }}"
    add_host:
      name: "{{ newvmip }}"
      groups: brandnewvm
    when: newvmip is defined



- hosts: brandnewvm
  roles:
    - kev-figlet
    - kev-motd
    - kev-nano
    - kev-screen
    - kev-standardsoftware
    - kev-users

