---
- name: Build a VMware guest from template
  hosts: localhost
  gather_facts: no

  tasks:
  - name: ROLE kev-vmware-provision
    include_role:
      name: kev-vmware-provision
    tags:
    - kev-vmware-provision

- hosts: brandnewvm
  roles:
    - kev-motd
    - kev-nano
    - kev-screen
    - kev-standardsoftware
    - kev-users

