---
- name: Build a VMware guest from template
  hosts: localhost
  gather_facts: no

  roles:
  - kev-vmware-provision
#  - kev-vmware-tag

- hosts: brandnewvm
  roles:
    - kev-figlet
    - kev-motd
    - kev-nano
    - kev-screen
    - kev-standardsoftware
    - kev-users

