---
- name: Build a VMware guest from template
  hosts: all
  connection: local
  gather_facts: no

  tasks:
    - block:
        roles:
        - kev-vmware-provision
      when: newvmip is not defined


  tasks:
    - block:
      - name: applying remaining roles to "{{ newvmip }}"
        add_host:
          name: "{{ newvmip }}"
          groups: brandnewvm
      when: newvmip is defined


- hosts: brandnewvm
  roles:
    - kev-figlet
    - kev-motd
    - kev-nano
#    - kev-satelliteclientreg
    - kev-screen
    - kev-standardsoftware
    - kev-users

