---
- name: Build a VMware guest from template
  hosts: all
  connection: local
  gather_facts: no

  roles:
  - kev-vmware-provision

- hosts: brandnewvm
  roles:
    - kev-figlet
    - kev-motd
    - kev-nano
#    - kev-satelliteclientreg
    - kev-screen
    - kev-standardsoftware
    - kev-users

