---
- name: Build a VMware guest from template
  hosts: localhost
  gather_facts: no
  pipelining=True

  tasks:
  - name: "kev-vmware-provision if {{ newvmip } is not defined"
    include_role:
      name: kev-vmware-provision

- hosts: brandnewvm
  roles:
    - kev-figlet
    - kev-motd
    - kev-nano
    - kev-screen
    - kev-standardsoftware
    - kev-users

