---
- name: kev standards roles
  hosts: all
  become: yes
  gather_facts: true
  tasks:

#kev-figlet
#kev-standardsoftware
#kev-users
#satellite-reg.yaml
#shadowmansplash
#site.yml

  - name: include role kev-nano
    include_role:
      name: kev-nano
    tags:
    - kev-nano

  - name: include role kev-screen
    include_role:
      name: kev-screen
    tags:
    - kev-screen

  - name: include role kev-motd
    include_role:
      name: kev-motd
    tags:
    - kev-motd

  - name: include role kev-users
    include_role:
      name: kev-users
    tags:
    - kev-users

