- yum:
    name: "{{ satellite_url }}/pub/katello-ca-consumer-latest.noarch.rpm"

- redhat_subscription:
    state: present
    force_register: yes
    autosubscribe: yes
    activationkey: "{{ activation_key }}"
    org_id: "{{ organization }}"
    autosubscribe: "{{ autosub_yn }}"
#  when:
#    ansible_os_family : :  "Redhat" and ansible_distribution_major_version : :  "7"




