---
- name: MAIN | Deploying subtasks
  hosts: all
  remote_user: root

  vars:
    install_packages:
    - unzip
    - httpd
    - php
    - php-mysql
    - mariadb
    - mariadb-server
    - libselinux-python

  tasks:
    - name: install packages with yum
      yum:
        name: "{{ item }}"
        state: latest
      with_items: "{{ install_packages }}"

    - name: Retrieve and extract the wordpress.org/latest.zip file
      unarchive:
        src: https://wordpress.org/latest.zip
        dest: /var/www/html
        remote_src: True

#    - name: Grab the zip we have of WordPress
#      unarchive:
#        src: includes/wordpress-2017-01-01.zip
#        dest: /var/www/html

    - name: enable mariadb-server and restart it
      service:
        name: mariadb
        enabled: yes
        state: restarted

    - name: Change httpd.conf to make the web root "/var/www/html/wordpress"
      lineinfile:
        dest: /etc/httpd/conf/httpd.conf
        regexp: '^DocumentRoot '
        line: 'DocumentRoot "/var/www/html/wordpress"'

    - name: create our mysql.sql with permissions for the WordPress database
      raw: mysql  -e "create database wordpress; GRANT ALL PRIVILEGES ON wordpress.* TO wordpress@localhost IDENTIFIED BY 'redhat'"
      ignore_errors: yes

    - name: copy a fun template of some variables
      template:  
        src: includes/system-info.txt
        dest: /root/system-info.txt
        owner: root
        group: root
        mode: 0644

    - name: copy our wordpress template sql dumps
      template:  
        src: includes/wordpress.sql
        dest: /tmp/wordpress.sql
        owner: root
        group: root
        mode: 0644

    - name: import wordpress.sql to our wordpress server
      raw: 'mysql wordpress < /tmp/wordpress.sql'
      ignore_errors: yes

    - name: copy our existing config to the site
      copy:  
        src: includes/wp-config.php
        dest: /var/www/html/wordpress/wp-config.php
        owner: apache
        group: apache
        mode: 0644
        backup: yes

    - name: copy our custom logo to the site
      copy:  
        src: includes/header_ansible.jpg 
        dest: /var/www/html/wordpress/wp-content/themes/twentyseventeen/assets/images/header.jpg
        owner: apache
        group: apache
        mode: 0644
        backup: yes

    - name: enable firewall for http traffic
      firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled
      ignore_errors: yes

    - name: enable http and restart it
      service:
        name: httpd
        enabled: yes
        state: restarted

