- name: Install EPEL repo.
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present

- name: Import EPEL GPG key.
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
    state: present


- name: figlet installation
  yum:
    name: figlet
    state: latest

- name: copy over the extra fonts
  copy:
    src: files/figletfonts/
    dest: /usr/share/figlet/

#- name: add figlet hostname to MOTD
#  raw: figlet -f rectangles `hostname -f` >> /etc/issue
