---
# defaults file for kev-vmware-provision/---

vc_hostname: 10.0.30.200
vc_username: kev
vc_password: kev
vc_datacenter: KevDC
vm_template: 'KEV - CentOS7'
vm_name: GoKEV-newvm-00000
vm_cluster: KevCluster
vm_guestid: centos64Guest
vm_cpu_count: 1
vc_datastore: vsanDatastore
vm_disk_size: 20
vm_folder: /
vm_network: VM Network
vm_ram_mb: 1024
vm_state: poweredon
validate_certs: no

