---
# defaults file for kev-vmware-provision/---

vc_hostname: vcenter.lab
vc_username: username
vc_password: password
vc_datacenter: KevDC
vm_template: kev-template
vm_name: GoKEV-newvm-00000
vm_cluster: KevCluster
vm_guestid: centos64Guest
vm_cpu_count: 1
vc_datastore: vsanDatastore
vm_disk_size: 20
vm_folder: /
vm_network: VM Network
vm_ram_mb: 1024
vm_state: poweredon
validate_certs: no

