---
# tasks file for kev-dns-change---

#	"ansible_distribution": "CentOS", 
#        "ansible_distribution_file_parsed": true, 
#        "ansible_distribution_file_path": "/etc/redhat-release", 
#        "ansible_distribution_file_variety": "RedHat", 
#        "ansible_distribution_major_version": "7", 



- name: Include task list in play
  include: dns_centos.yml
  when: ansible_distribution == "CentOS"

- name: Include task list in play
  include: dns_el6.yml
  when: ansible_distribution == "RedHat"

- name: Define the custom MOTD file if this is a RHEL system
  set_fact:
    motd_template_file: templates/motd_redhat

- name: Define the MOTD file for any non-RHEL and non-CENT machine
  set_fact:
    motd_template_file: templates/motd_generic
  when: ansible_distribution != "CentOS" and ansible_distribution != "RedHat"

- name: motd template
  template:
    src: "{{ motd_template_file }}"
    dest: /etc/motd
    owner: root
    group: wheel
    mode: 0644
    backup: yes

- name: issue template
  template:
    src: templates/issue
    dest: /etc/issue
    owner: root
    group: wheel
    mode: 0644
    backup: yes

