- name: GET SOME STUFF
  hosts: localhost
  remote_user: root

  tasks:
  - debug:
      msg: "kev_message is {{ kev_message }}"
    when: kev_message is defined

  - debug:
      msg: "Message is {{ some_message }}"
    when: some_message is defined

  - debug:
      msg: "Variable is {{ some_variable }}"
    when: some_variable is defined
